audio_settings:
  wake_word: "Emma"
  wake_word_timeout: 30
  wake_word_buffer_size: 3.0
  wake_check_interval: 0.5
  chunks: 512
  channels: 1
  sample_rate: 16000
  threshold: 400
  barge_in_rms: 3000
  barge_in_confidence: 0.7

location: "Kichha, Uttarakhand"

brain_settings:
  worker_llm: "openai/gpt-oss-120b"
  supervisor_llm: "llama-3.1-8b-instant"

voice_settings:
  model: "./piper_voices/en_GB-cori-high.onnx"

memory_settings:
  path: "memory_db"
  embedding_model: "all-MiniLM-L6-v2"
  